[#175476527] Release pipeline and pipeline refactor
pagopa/io-functions-app pull request #123
Opened 2020-12-01 14:35 UTC by balanza

Save changes applied in https://github.com/pagopa/io-functions-services/pull/96.

### Changes in brief
* Introduce the `Release` stage on the pipeline which marks a release on the repository
* Remove `release-it` scripts and use plain `npm version` instead
* Refactor the whole CI/CD to have 
  * separated pipelines for code review and deploy scenarios
  * everything is into `.devops` folder now

2020-12-01 18:31 UTC, balanza commented
/azp run

2020-12-02 08:41 UTC, balanza commented
Pipelines configured in Azure DevOps

2020-12-02 12:34 UTC, gunzip commented on .devops/deploy-pipelines.yml
> +              endpoint: 'https://$(PRODUCTION_APP_NAME)-staging.azurewebsites.net/api/info'
```suggestion
              endpoint: 'https://$(PRODUCTION_APP_NAME)-staging.azurewebsites.net/api/v1/info'
```

2020-12-02 12:35 UTC, gunzip commented
why draft?

2020-12-02 12:53 UTC, balanza commented
/azp run

2020-12-03 10:20 UTC, balanza commented
/azp run

2020-12-03 11:39 UTC, pasqualedevita requested changes
healthcheck ok

2020-12-03 11:39 UTC, pasqualedevita commented on .devops/deploy-pipelines.yml
> +                !tsconfig.json
```suggestion
                **/*
                !.git/**/*
                !**/*.js.map
                !**/*.ts
                !.vscode/**/*
                !.devops/**/*
                !.prettierrc
                !.gitignore
                !README.md
                !jest.config.js
                !local.settings.json
                !test
                !tsconfig.json
                !tslint.json
                !yarn.lock
                !Dangerfile.js
                !CODEOWNERS
                !__*/**/*
```

added `!.devops/**/*` removed `!azure-templates/**/*`
others from fn-admin

2020-12-03 14:17 UTC, gunzip commented
can we merge this one?

2020-12-03 15:36 UTC, merged