[#176095347] deploy to multiple app services
pagopa/io-functions-app pull request #136
Opened 2020-12-16 15:01 UTC by balanza

Edit the deploy pipeline to support multiple app services at the same time.

The set of app services to deploy to is stored a map parameter. 
A readonly variable might have been a better fit as parameters can be edited manually before executing the pipeline, however. Azure does not support map in variables. Anyway, **users aren't supposed to edit this value at runtime**.

### Behaviour
* make a release
* build the application once
* deploy and healthcheck on every app service in parallel
* wait for every healthcheck to be executed, then swap every app to production; this means that if only one of the three apps fails on its staging slot, the others won't be promoted to production neither.
![Screenshot 2020-12-16 at 15 53 41](https://user-images.githubusercontent.com/265564/102364635-fad82880-3fb6-11eb-80f5-e159c93db10e.png)

### Changes
* App names and resource groups are now hard-coded in the pipeline yaml rather than being provided by pipeline configuration. We decided this makes sense as the infrastructure code as well treat such values as string literals in the codebase. This also means that we might remove unused variables from pipeline configuration when these changes are merged.

2020-12-16 17:43 UTC, pasqualedevita requested changes

2020-12-16 17:43 UTC, pasqualedevita commented on .devops/deploy-pipelines.yml
> +            displayName: 'ls System.DefaultWorkingDirectory<'
```suggestion
```
remove only for debug

2020-12-16 17:43 UTC, pasqualedevita commented on .devops/deploy-pipelines.yml
> +
```suggestion
```
remove only debug

2020-12-16 17:45 UTC, pasqualedevita commented
@balanza big work!! 💯

2020-12-16 20:23 UTC, gunzip commented
So, is this another pipeline that will live aside the other ones (the actual ones that we use to deploy to a singl app service) ?
I'm asking since the chance to chose just one between the app services to deploy it's a really useful feature.

2020-12-16 21:42 UTC, pasqualedevita commented
yes now there are three pipelines, one for each app service.
This pipeline can deploy on all app service by default but if needed we can deploy only to one app service editing this parameter before run the pipeline (for example delete `appAsync` section)
```
app1:
  appname: io-p-fn3-app1
  rg: io-p-rg-functions_app1
app2:
  appname: io-p-fn3-app2
  rg: io-p-rg-internal
```
<img width="484" alt="Screenshot 2020-12-16 at 22 40 27" src="https://user-images.githubusercontent.com/59291437/102409661-bcab2b00-3fef-11eb-85e5-a1a4128719fb.png">

2020-12-16 21:59 UTC, gunzip approved these changes

2020-12-17 09:05 UTC, balanza commented
> So, is this another pipeline that will live aside the other ones (the actual ones that we use to deploy to a singl app service) ?
> I'm asking since the chance to chose just one between the app services to deploy it's a really useful feature.

No, this will replace all the other deploy pipelines and serve as the only entry point for deploying.

I advocate we should always deploy a new version to every production app service.

Even though,  as @pasqualedevita said, it is indeed possible to hack the pipeline to consider only one or two of the app services. Please note that the pipeline also marks a new version of the app, thus we have to take care of this when deploying separately (manually disabling the release stage, probably).

2020-12-17 10:23 UTC, pasqualedevita requested changes

2020-12-17 10:23 UTC, pasqualedevita commented on .devops/deploy-pipelines.yml
> +            displayName: 'ls System.DefaultWorkingDirectory<'
@balanza can we remove also this?

2020-12-17 14:49 UTC, pasqualedevita approved these changes

2020-12-17 15:02 UTC, merged