fix - pagopa web site url
pagopa/io-functions-app pull request #201
Opened 2021-08-24 19:09 UTC by Undermaken

atm a new IO user can't browser [pagopa web site](https://www.pagopa.it/)

| welcome message  | pagopa |
| ------------- | ------------- |
![welcome message](https://user-images.githubusercontent.com/822471/130675490-4dcb5398-5858-4d2e-8247-8600c8cf8e11.jpg) | ![pagopa](https://user-images.githubusercontent.com/822471/130675501-0eaefcb4-4c9a-4359-98fb-b66c11ce2a3d.jpg)

2021-08-24 20:51 UTC, thisisjp commented on SendWelcomeMessagesActivity/handler.ts
> +IO integra [pagoPA](https://www.pagopa.it/) per effettuare pagamenti sicuri verso la Pubblica Amministrazione. Dalla sezione Portafoglio puoi aggiungere i tuoi metodi di pagamento preferiti, proceder
```suggestion
IO integra [pagoPA](https://www.pagopa.gov.it/) per effettuare pagamenti sicuri verso la Pubblica Amministrazione. Dalla sezione Portafoglio puoi aggiungere i tuoi metodi di pagamento preferiti, procedere al pagamento di un avviso pagoPA (tramite scansione del codice QR o inserimento manuale del codice avviso) e tenere traccia di tutte le operazioni svolte. Se hai già usato pagoPA con SPID in passato, nella sezione Portafoglio potrai vedere lo storico delle transazioni effettuate e i tuoi metodi di pagamento salvati. 
```

2021-08-24 20:52 UTC, thisisjp requested changes
The problem is the missing www.

pagopa.it is The corporate website, while here we’re referring to the payment platform :)

2021-08-24 21:19 UTC, Undermaken commented
> The problem is the missing www.
> 
> pagopa.it is The corporate website, while here we’re referring to the payment platform :)

I'll never be able to remember the difference
It's something like this
![Screenshot_2021-08-24-23-16-53-350_com.android.chrome.jpg](https://user-images.githubusercontent.com/822471/130691455-72661aa7-948f-4f6a-8b77-28dbd09a4f92.jpg)

2021-08-25 06:26 UTC, vito80ba approved these changes

2021-08-25 07:59 UTC, merged