test pr
pagopa/io-functions-app pull request #208
Opened 2021-09-10 15:06 UTC by balanza

2021-09-10 15:07 UTC, BurnedMarshal approved these changes
test approve

2021-09-13 07:03 UTC, michaeldisaro requested changes

2021-09-13 07:03 UTC, michaeldisaro commented on utils/config.ts
> +  t.partial({
Why not extracting partials like what happen in models?

2021-09-13 07:04 UTC, michaeldisaro commented on GetVisibleServices/handler.ts
> +  toServicesTuple(new StrMap(serviceJson)).reduce(
I see this PR is based on fp-ts 1.14. Did you branched from an updated master?

2021-09-13 07:38 UTC, closed without merging