[#IP-182] Upgrade GetMessage model with payee
pagopa/io-functions-app pull request #219
Opened 2021-10-01 16:02 UTC by AleDore

#### List of Changes

#### Motivation and Context

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2021-10-04 08:42 UTC, gquadrati requested changes
LGTM, just a few comments. Also, did you try it on io-mock env?

2021-10-04 08:42 UTC, gquadrati commented on GetMessage/handler.ts
> +      return E.left<IResponseErrorInternal, O.Option<PaymentData>>(
There is no need of defying types

2021-10-04 08:42 UTC, gquadrati commented on GetMessage/handler.ts
> +      return E.left<IResponseErrorInternal, O.Option<PaymentData>>(
ditto

2021-10-04 08:42 UTC, gquadrati commented on GetMessage/handler.ts
> +    return E.right<IResponseErrorInternal, O.Option<PaymentData>>(
ditto

2021-10-04 08:42 UTC, gquadrati commented on GetMessage/handler.ts
> +  return E.right<IResponseErrorInternal, O.Option<PaymentData>>(
ditto

2021-10-04 08:42 UTC, gquadrati commented on GetMessage/handler.ts
> +const getErrorOrPaymentData = async (
Please, add a brief description.

2021-10-04 09:27 UTC, michaeldisaro approved these changes
Apart some non functional code, that's used pretty commonly, and @gquadrati notes, I think it's ok.

2021-10-04 09:35 UTC, gquadrati commented on GetMessage/handler.ts
> +  if (
I noticed that too, I thought it was for not mixing old imperative code with functional one.

2021-10-04 09:37 UTC, michaeldisaro commented on GetMessage/handler.ts
> +  if (
I think that the new code should me as more functional as possible... but by the way I don't think it's a reason to block a PR if the code maintains a style that's coherent with other code. I would have requested changes if the code would have changed style.

2021-10-04 09:43 UTC, gquadrati commented on GetMessage/handler.ts
> +  if (
I agree

2021-10-04 10:11 UTC, gquadrati commented on GetMessage/__tests__/handler.test.ts
> +  it("should respond with a message payment data overriden with payee if original content does not have a payee", async () => {
Did we test the case when a payee is present?

2021-10-05 07:28 UTC, gquadrati approved these changes
LGTM

2021-10-12 13:55 UTC, merged