[#IOCIT-9] Updated profile handlers to accept the new optional field from the profile model
pagopa/io-functions-app pull request #255
Opened 2022-06-21 09:30 UTC by arcogabbo

This PR depends on #252 

#### List of Changes

Updated `io-functions-commons` dependency to take the new model.
Updated `io-ts-commons` dependency to take `Semver` type.
Updated the profile handlers tests 
Updated profile handlers to correctly manipulate the new field

#### Motivation and Context

Correctly accept the optional field

#### How Has This Been Tested?

Build and tests passed

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2022-06-21 09:36 UTC, arcogabbo commented on CreateProfile/__tests__/handler.test.ts
> -/* eslint-disable @typescript-eslint/no-explicit-any */
I removed the linter ignoring comments because the tests file are ignored by eslint.

2022-06-21 14:40 UTC, BurnedMarshal requested changes

2022-06-21 14:40 UTC, BurnedMarshal commented on UpdateProfile/__tests__/handler.test.ts
> +      findLastVersionByModelId: jest.fn(() => TE.of(some({ ...aRetrievedProfile, lastAppVersion: undefined }))),
This should never happen. The decode of the `findLastVersionByModelId` model method adds the default value.

2022-06-21 14:40 UTC, BurnedMarshal commented on UpdateProfile/__tests__/handler.test.ts
> +      findLastVersionByModelId: jest.fn(() => TE.of(some({ ...aRetrievedProfile, lastAppVersion: "0.0.1" }))),
`lastAppVersion` override is not needed here, `aRetrievedProfile` already has it.
```suggestion
      findLastVersionByModelId: jest.fn(() => TE.of(some(aRetrievedProfile))),
```

2022-06-21 15:27 UTC, BurnedMarshal approved these changes
LGTM apart a minor change.
Wait for #252 to be merged before merging this pull request.

2022-06-23 10:33 UTC, BurnedMarshal requested changes

2022-06-23 10:33 UTC, BurnedMarshal commented on openapi/index.yaml
> +        $ref: '#/definitions/Profile/properties/last_app_version'
To avoid nested type import we should import the `AppVersion` type in `index.yaml.template`

2022-06-27 07:09 UTC, merged