[#IOPID-384] notice login email durable function
pagopa/io-functions-app pull request #283
Opened 2023-07-11 07:45 UTC by arcogabbo

This PR depends on #281
This PR depends on https://github.com/pagopa/io-messages-email-templates/pull/13

#### List of Changes

* added 3 activities: `SendTemplatedLoginEmailActivity`,`GetMagicCodeActivity`,`GetGeoLocationDataActivity`
* added 1 orchestrator: `NoticeLoginEmailOrchestrator`
* added 1 trigger: `NoticeLoginEmailTrigger`

#### Motivation and Context

sending an email whenever a user completes a full login flow

#### How Has This Been Tested?

unit tests

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2023-07-11 17:44 UTC, gquadrati requested changes

2023-07-12 07:44 UTC, arcogabbo commented on NoticeLoginEmailTrigger/__tests__/handler.test.ts
> +    result.apply(res);
nice catch. solved in https://github.com/pagopa/io-functions-app/pull/283/commits/5d3bbbbe32125b4f85d59f551ce72f2aff3b68d5

2023-07-12 08:15 UTC, arcogabbo commented on SendTemplatedLoginEmailActivity/handler.ts
> +          );
done in https://github.com/pagopa/io-functions-app/pull/283/commits/5d3bbbbe32125b4f85d59f551ce72f2aff3b68d5

2023-07-12 08:15 UTC, arcogabbo commented on SendTemplatedLoginEmailActivity/index.ts
> +const EMAIL_TITLE = "LOGIN EMAIL";
done in https://github.com/pagopa/io-functions-app/pull/283/commits/5d3bbbbe32125b4f85d59f551ce72f2aff3b68d5

2023-07-12 08:15 UTC, arcogabbo commented on GetGeoLocationDataActivity/handler.ts
> +      )
done in https://github.com/pagopa/io-functions-app/pull/283/commits/5d3bbbbe32125b4f85d59f551ce72f2aff3b68d5

2023-07-12 08:16 UTC, arcogabbo commented on NoticeLoginEmailOrchestrator/handler.ts
> +  );
I hashed all the values you mentioned plus the email in https://github.com/pagopa/io-functions-app/pull/283/commits/5d3bbbbe32125b4f85d59f551ce72f2aff3b68d5. thank you for the recommendation.

2023-07-12 08:16 UTC, arcogabbo commented on NoticeLoginEmailOrchestrator/handler.ts
> +  } = orchestratorInput;
done in https://github.com/pagopa/io-functions-app/pull/283/commits/5d3bbbbe32125b4f85d59f551ce72f2aff3b68d5

2023-07-12 08:16 UTC, arcogabbo commented on NoticeLoginEmailTrigger/__tests__/handler.test.ts
> +    expect(result.kind).toBe("IResponseErrorInternal");
done in https://github.com/pagopa/io-functions-app/pull/283/commits/5d3bbbbe32125b4f85d59f551ce72f2aff3b68d5

2023-07-12 09:04 UTC, BurnedMarshal commented on NoticeLoginEmailTrigger/index.ts
IMHO the folder name should be without the `Trigger` suffix. (es. `NoticeLoginEmail`)

2023-07-12 09:06 UTC, arcogabbo commented on GetGeoLocationDataActivity/handler.ts
> +          E.toError
done in https://github.com/pagopa/io-functions-app/pull/283/commits/40abd733fc1a1797b76bebbfdca9a860f6c0928d

2023-07-12 09:06 UTC, arcogabbo commented on NoticeLoginEmailOrchestrator/handler.ts
> +        });
done in https://github.com/pagopa/io-functions-app/pull/283/commits/40abd733fc1a1797b76bebbfdca9a860f6c0928d

2023-07-12 09:07 UTC, arcogabbo commented on NoticeLoginEmailOrchestrator/handler.ts
> +    }
done in https://github.com/pagopa/io-functions-app/pull/283/commits/40abd733fc1a1797b76bebbfdca9a860f6c0928d

2023-07-12 09:07 UTC, arcogabbo commented on GetMagicCodeActivity/handler.ts
> +    ),
done in https://github.com/pagopa/io-functions-app/pull/283/commits/40abd733fc1a1797b76bebbfdca9a860f6c0928d

2023-07-12 09:39 UTC, arcogabbo commented on NoticeLoginEmailTrigger/index.ts
done in https://github.com/pagopa/io-functions-app/pull/283/commits/067b2282ce86b9aeab060de9a9911bda60f6ece6

2023-07-12 09:44 UTC, arcogabbo commented
> SonarCloud Quality Gate failed.    [![Quality Gate failed](https://camo.githubusercontent.com/4ea51c1f64ee3746f631653a02ab678ca6a3efb5f5cb474402faed2e3dcf90b5/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f5175616c6974794761746542616467652f6661696c65642d313670782e706e67)](https://sonarcloud.io/dashboard?id=pagopa_io-functions-app&pullRequest=283)
> 
> [![Bug](https://camo.githubusercontent.com/4c6102327f5a954f9c8acaf2e2714183157a9e41717b371b2cd585cf25057310/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f6275672d313670782e706e67)](https://sonarcloud.io/project/issues?id=pagopa_io-functions-app&pullRequest=283&resolved=false&types=BUG) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/issues?id=pagopa_io-functions-app&pullRequest=283&resolved=false&types=BUG) [0 Bugs](https://sonarcloud.io/project/issues?id=pagopa_io-functions-app&pullRequest=283&resolved=false&types=BUG) [![Vulnerability](https://camo.githubusercontent.com/3ba1ee49636ffc3427e38649a9f8a65ee392f28e8a662fcf96ce24cefbb520e9/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f76756c6e65726162696c6974792d313670782e706e67)](https://sonarcloud.io/project/issues?id=pagopa_io-functions-app&pullRequest=283&resolved=false&types=VULNERABILITY) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/issues?id=pagopa_io-functions-app&pullRequest=283&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=pagopa_io-functions-app&pullRequest=283&resolved=false&types=VULNERABILITY) [![Security Hotspot](https://camo.githubusercontent.com/fb735cbe76f8d5e1679c76ce83b740ceb1eaf62de4f7bf88623dc9953261aff7/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f73656375726974795f686f7473706f742d313670782e706e67)](https://sonarcloud.io/project/security_hotspots?id=pagopa_io-functions-app&pullRequest=283&resolved=false&types=SECURITY_HOTSPOT) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/security_hotspots?id=pagopa_io-functions-app&pullRequest=283&resolved=false&types=SECURITY_HOTSPOT) [0 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=pagopa_io-functions-app&pullRequest=283&resolved=false&types=SECURITY_HOTSPOT) [![Code Smell](https://camo.githubusercontent.com/8fe18b2dfb6f7d4e44582f281b29f617eb5ae07c248d2002ca586e91da219212/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f636f64655f736d656c6c2d313670782e706e67)](https://sonarcloud.io/project/issues?id=pagopa_io-functions-app&pullRequest=283&resolved=false&types=CODE_SMELL) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/issues?id=pagopa_io-functions-app&pullRequest=283&resolved=false&types=CODE_SMELL) [0 Code Smells](https://sonarcloud.io/project/issues?id=pagopa_io-functions-app&pullRequest=283&resolved=false&types=CODE_SMELL)
> 
> [![No Coverage information](https://camo.githubusercontent.com/86785eaa572e061f5ecb3f8bf1cbb7b8eca44925083f92d067805b4362cead0c/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f436f76657261676543686172742f4e6f436f766572616765496e666f2d313670782e706e67)](https://sonarcloud.io/component_measures?id=pagopa_io-functions-app&pullRequest=283) No Coverage information [![5.6%](https://camo.githubusercontent.com/6d10b2752bda1e1762d255930f4a4807428112b982706db9e339669f1165f525/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f4475706c69636174696f6e732f31302d313670782e706e67)](https://sonarcloud.io/component_measures?id=pagopa_io-functions-app&pullRequest=283&metric=new_duplicated_lines_density&view=list) [5.6% Duplication](https://sonarcloud.io/component_measures?id=pagopa_io-functions-app&pullRequest=283&metric=new_duplicated_lines_density&view=list)
> 
> ![idea](https://camo.githubusercontent.com/00150338e138e454e357462ed3d9cfceaf338ca50ccadcc1f3a75ad6a0e2aab2/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f6c696768745f62756c622d313670782e706e67) Catch issues before they fail your Quality Gate with our IDE extension ![sonarlint](https://camo.githubusercontent.com/e4a8f808c72d84f231c1400ce7f2c77a09afe3eadb6bde9ad2c208a46735d320/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f736f6e61726c696e742d313670782e706e67) [SonarLint](https://www.sonarsource.com/products/sonarlint/features/connected-mode/?referrer=sonarcloud-welcome)

this duplication error will be removed after we implement the actual logic and the actual service clients

2023-07-12 09:53 UTC, gquadrati approved these changes
LGTM, good work! 🚀  Thanks @arcogabbo

2023-07-13 07:53 UTC, merged