[#IOPID-2331] `FF_UNIQUE_EMAIL_ENFORCEMENT` removal
pagopa/io-functions-app pull request #317
Opened 2024-10-04 08:09 UTC by salvatorelaiso

#### List of Changes
Remove Feature Flag `FF_UNIQUE_EMAIL_ENFORCEMENT` and its usage from `GetProfile` and `UpdateProfile`.
Linting.

#### Motivation and Context
The Feature Flag `FF_UNIQUE_EMAIL_ENFORCEMENT` is not needed anymore.

#### How Has This Been Tested?
Unit tests.

#### Screenshots (if appropriate):

#### Types of changes

- [x] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-10-07 12:54 UTC, arcogabbo requested changes
it seems you forgot the variable `FF_UNIQUE_EMAIL_ENFORCEMENT` inside `IConfig` decoder in `config.ts` file

2024-10-07 13:41 UTC, salvatorelaiso commented
> it seems you forgot the variable `FF_UNIQUE_EMAIL_ENFORCEMENT` inside `IConfig` decoder in `config.ts` file

Solved in [ed8c8d7](https://github.com/pagopa/io-functions-app/pull/317/commits/ed8c8d7595334f534aca4d47a8009d1b6aa13be1)

2024-10-07 14:54 UTC, arcogabbo approved these changes

2024-10-07 16:07 UTC, gquadrati requested changes
LGTM, I just left a small comment

2024-10-08 09:33 UTC, salvatorelaiso commented on utils/config.ts
> -    FF_UNIQUE_EMAIL_ENFORCEMENT: FeatureFlagFromString,
Solved in 2c19952

2024-10-08 14:31 UTC, merged